### ISSUE TITLE
setting bufferDelay on mixin instead of BUFFER_DELAY constant

### ISSUE THREAD

**Issue by nhemsley** [mitchlloyd/ember-autosave#11]
Hey,

I would like to be able to set the buffer delay per controller, which necessitates having it as an overrideable value on the Ember.AutoSaving mixin:

bufferedDelay: 1000

However, due to the context in which _debouncedSave is run (or something thereabouts), @bufferDelay does not work, i.e.

  _debouncedSave: Ember.debounce (-> @_safeSave()), @bufferDelay

will not work, as @ (or this) is the window object.

This is not a bug per se, but perhaps a feature request & any help would be much appreciated.

I can put up a fork branch if that helps to illustrate the case.

**Comment by mitchlloyd** [comment]
Yeah, this seems obvious in retrospect. Would love it if you could put together a PR.

There should probably just be a bufferDelay property in the mixin that can be overridden.

**Comment by mitchlloyd** [comment]
Fixed by 3b25625e001f59ffd88cf17b12d94ee7cc192fb2

It's now possible to configure the `saveDelay` property globally with `AutosaveProxy.config()` or per instance.
