### ISSUE TITLE
object proxying is deprecated

### ISSUE THREAD

**Issue by bfcoder** [mitchlloyd/ember-autosave#12]
Do you have any ideas on how to get this working with ember now that object proxying is deprecated in Ember 1.11.1? Because the setUnknownProperty does not work unless you are doing object proxying (using ```model.attribute``` is now how you have to reference your attributes instead of doing object proxying by just using ```attrubute```). Or at least that is what I have been able to figure out. Maybe I'm wrong?

**Comment by mitchlloyd** [comment]
Could you expand on what you mean by "object proxying is deprecated"? Is there a specific deprecation you're thinking of that you could point me to?

ObjectController and ArrayController are deprecated and, after reading your issue, I noticed that the description of this project on Github ("A controller mixin...") is no longer accurate. I updated that.

Take a look at the readme, the new way to use this is to wrap your model in a ProxyObject.

**Comment by bfcoder** [comment]
If you look at http://emberjs.com/deprecations/v1.x/#toc_objectcontroller you'll see that you can no longer do ```{{modelPropertyName}}``` and you have to do ```{{model.modelPropertyName}}```

Well the autosave uses ```setUnknownProperty``` which relies on the object being a proxy ( ```{{modelPropertyName}}```). If it isn't a proxy and directly accessing the property (```{{model.modelPropertyName}}```), then it doesn't use ```setUnknownProperty``` and thus changes to that property are not seen by the autosave code.

I am however using code from a [fork](https://github.com/bfcoder/ember-autosaving) of your code that isn't for Ember-cli. So I'll have to look into wrapping my model into a ProxyObject.

Do you have your code working in Ember 1.11.1?

**Comment by bfcoder** [comment]
I converted your code over to non-cli (or rather to es5) and wrapped one of my models in an ```Ember.ObjectProxy``` and seems to work fine. Not sure it will continue to be supported with Ember, but for now I'll dump the way I'm currently doing this. Thanks!

**Comment by mitchlloyd** [comment]
@bfcoder I wouldn't worry about ObjectProxy going away anytime soon. Projects like this and [Buffered Proxy](https://github.com/yapplabs/ember-buffered-proxy) use this pattern with a lot of success.

**Comment by mrloop** [comment]
@bfcoder have a look at [GiftWrap](https://github.com/ef4/ember-giftwrap) for using ember-cli addons in non ember-cli projects. Have successfully used it with ember-autosave.
