### ISSUE TITLE
DEPRECATION: Use get/set functions in computed properties

### ISSUE THREAD

**Issue by jackweinbender** [mitchlloyd/ember-autosave#15]
Is there any interest in using [the newer syntax ][1] for getters and setters in computed properties? The current implementation gives deprecation warnings in the latest 1.13 release. However, I think it would be a breaking change for pre-1.12 apps.

[1]: http://emberjs.com/deprecations/v1.x/#toc_deprecate-using-the-same-function-as-getter-and-setter-in-computed-properties

**Comment by mitchlloyd** [comment]
I would be interested in a PR for that, I don't want this library to add to anyone's deprecations. Thanks for filing the issue.

I figure this is a breaking change for old apps, so I'll probably tag this as 1.0. We'll say 1.0 is targeted at 1.13 and 2.x Ember releases.

**Comment by mitchlloyd** [comment]
Closed by #16.
