### ISSUE TITLE
General usage question

### ISSUE THREAD

**Issue by kynetiv** [mitchlloyd/ember-autosave#19]
Hi, I’m interested in this project but initially having some issues setting up a very basic implementation and not having much luck getting the demo to work either. I’m hoping someone can answer some general usage questions or provide any pointers as to what I’m doing wrong. I'd also be happy to take this question somewhere else if this isn't the right place for it.

I’m using Ember 1.13.11 and Ember-Autosave 1.0.0 (facing similar challenges using the 0.3.0 branch).

I have a component that has a model property ‘percent’ passed in from another component. I’d like this ‘percent’ to be set up to 'autosave'.

```javascript
{{!templates/components/main-control.hbs }}

{{percent-control percent=percent}}

```

```javascript
//components/percent-control.js
import Ember from ‘ember’;
import autosave from ‘ember-autosave’;

 export default Ember.Component.extend({    
...

  percent: autosave(‘percent’),

...

```

On page load, I’m getting this:
  `Uncaught Error: Assertion Failed: You need to provide an object and key to ‘set’.`

For whatever reason the “set” method in computedAutsave is getting called at a point in which “proxy” is undefined and throws the above error:
```javascript
//computed-autosave.js
...

set: function(key, value, proxy){    
  set(proxy, 'content', value);   
  return proxy; 
}
...
```
Perhaps my autosave 'percent' property can’t be assigned to a property with the same name as a prop that was passed into my percent-control component? 

Testing this theory I modified my 'percent-control' component to:

```javascript
 export default Ember.Component.extend({    
...

  percentProxy: autosave(‘percent’),

...
```

 This does bypass the above error that was being thrown, and the input's onchange event seems to re-render my component template, but it's not saving the model. Any ideas?

**Comment by kynetiv** [comment]
After writing this up and running a few more tests, I've figured it out. For future reference to anyone coming here with my issue, whatever you pass to autosave (in my examples above it was 'percent') that parameter needs to be your model object (not the attribute value you want to autosave). The property you assign the autosave method to in you component/controller  will then be your reference to your _model_ and you use it in your inputs. Example here: 

```javascript

 export default Ember.Component.extend({    
...
  proxiedModel: autosave('model'),
...
```

```javascript
{{input value=proxiedModel.percent}}
```

**Comment by mitchlloyd** [comment]
Thanks for writing this up. Reading over the readme I can see that there is nothing to really explain exactly how this works. I'm going to take a look at it and see if I can make this clear.

**Comment by mitchlloyd** [comment]
I edited the readme attempting to clarify the more basic usage for wrapping an object inside of a component. https://github.com/mitchlloyd/ember-autosave/commit/d7ad38e07813010137b0aabb09e9520b3dfd1cae

I also added some descriptions to the demo to describe what is going on: https://github.com/mitchlloyd/ember-autosave/commit/6f0e9de93c9cc7737feef7cc4fb106b550d1988f

@kynetiv Let me know if you can think of anything else that would have helped the on-ramp process.
