### ISSUE TITLE
Setting a value to the same value on a plain `Ember.Object` causes a save

### ISSUE THREAD

**Issue by luxferresum** [mitchlloyd/ember-autosave#22]
Its cool that we can wrap a simple simple `Ember.Object`:

    base: Ember.computed({
		get() {
			return Ember.Object.create({
				quantity: 10
			});
		}
	}),
	data: autosave('base', {
		save(model) {
			console.log('This should never happen');
		}
	}),

But then a `set` on this will always trigger a `save()`, which is not ideal. In the above example this will trigger an `save`:

    Ember.set(this, 'data.quantity', 10);

I think that the autosave proxy should check equality in `setUnknownProperty`. Or is this an expected behaviour?

**Comment by mitchlloyd** [comment]
Doing a strict equality check before firing `save` seems reasonable to me. This does mirror the behavior of observers and computed properties. My only reservation is that it _could_ mean something to `set(obj, 'a', 'foo')` on `{a: 'foo'}` if server data is out of sync with the local data.

If this were the case, it seems that we would still call set on the model even if the value hadn't changed, just in case someone has setup more proxy behavior there.

Another option to consider is passing a data structure with the previous and new values to `save` (`{property: 'quantity', previousValue: 10, currentValue: 10`) That would let the author of the `save` callback make some decisions about when to save.

Let me know what you think, but off hand I would be happy for a PR to add this check before calling save.

**Comment by luxferresum** [comment]
I think for now we are good with checking equality. For this very special use case you mentions I think the better solution is another hook, like `calledSet()`. There you could use a data structure like used by `ember-data`. But I'm not sure if anyone would need it.
