### ISSUE TITLE
object proxy does not update when record is updated after loading

### ISSUE THREAD

**Issue by remkoboschker** [mitchlloyd/ember-autosave#25]
I have a child component that has a model that is a relationship of the parent components model. This child component has an autosave object proxy. When I show a property of the proxied object it does not show up. I think this is because the value of the component object being undefined at render and becoming the required value as the async relationship resolves. 
````
{{#parent-component post=post}}
 {{#each post.tags as |tag|}}
    {{child-component tag=tag}}
  {{/each}}
{{/parent-component}}

{{#child-component}}
  {{tagProxy.name}} {{!-- undefined --}}
{{/child-component}}
````

**Comment by remkoboschker** [comment]
Deferring setting the proxy until the model is in a ready state solves the issue. Perhaps this can be integrated into `ember-autosave` proper.
````
// app/components/child-component/component.js
import Ember from 'ember';
import autosave from 'ember-autosave';

export default Ember.Component.extend({
  tagProxy: null,
  init(){
   this.get('tag').on('ready', () => this.set('tagProxy', autosave('tag'));
  }
});
````

**Comment by mitchlloyd** [comment]
I'm 👍  on loading data inside of components and don't feel like it's an anti-pattern.

I have a couple of thoughts. Sometimes it's nice to separate the component that is responsible for data loading from the component the renders that data. Those React yahoos call this [container vs presentational components](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.fmotdijhl).  Having a container component responsible for resolving the `tag` model would make the computed pattern work.

However, it also seems reasonable to setup the autosave proxy in a component lifecycle hook like `init`. What you've shown works, but in this case I would recommend using the `AutosaveProxy` class directly as the [readme shows](https://github.com/mitchlloyd/ember-autosave#using-autosaveproxy). 

Let me know what you think about using the autosave proxy class as shown in the readme and if you think there is some way this library could better support this use case.

**Comment by remkoboschker** [comment]
Thank you for your answer.

Do I understand you correctly that using the `AutosaveProxy` class directly should not require waiting for the model to be ready? I have tried and it does seems to require the ready event. Why do you recommend not using the computed property?

Thank you for the link to the article. I have been struggling a bit trying to make components stateless / functional that have to do some loading or saving. Splitting things up into container and presentational components seems like a good way forward.

Over the weekend I actually refactored the application to do all the loading in the route. But it becomes a bit messy, because it is an admin interface that needs to load a lot of different templates and configurations depending on what particular part of the service the admin wants to configure.
