### ISSUE TITLE
Unclear usage documentation

### ISSUE THREAD

**Issue by simenheg** [mitchlloyd/ember-autosave#27]
The section [Using AutosaveProxy](https://github.com/mitchlloyd/ember-autosave#using-autosaveproxy) in the README shows an example where `didReceiveAttrs` is implemented in a route.

As far as I know, `didReceiveAttrs` is a component method. How is this intended to work? I think a clarification or a correction in the documentation would be good.

**Comment by mitchlloyd** [comment]
Ah that this totally a "too much copy and paste" mistake. I'll fix that up.

**Comment by mitchlloyd** [comment]
Thanks for opening this issue. Let me know if you run across any other errors or if there's anything that needs clarification.
