### ISSUE TITLE
Chenged properties on autosaved object do not trigger rerender

### ISSUE THREAD

**Issue by luxferresum** [mitchlloyd/ember-autosave#28]
Hello

I was able to reproduce this problem on a fresh ember 2.6 app.

Assume we have this code in a component/controlleR:

```
bar: Ember.computed({
  get() {
    return Ember.Object.create({value:10});
  }
}),
foo: autosave('bar', {
  save(model) {
    console.log('save', model);
  }
}),
```

And a template like this:

```
bar: {{bar.value}}<br />
foo: {{foo.value}}<br />
```

Then we see:

> bar: 10
> foo: 10

But now when we do something like this (for example in an actions):

```
set(get(this, 'bar'), 'value', 7);
```

We end up seeing this:

> bar: 7
> foo: 10

Btw, a simple `get(this, 'foo.value')` will return the correct `7`. Just the template does not rerender.

**Comment by mitchlloyd** [comment]
I believe I understand what is happening, but I don't think there is a practical solution for this. For this to work, the proxy would somehow need to observe every change that happens to it's underlying subject.

Could you provide some information about your specific use case to see if there is some other possible approach?
