### ISSUE TITLE
Ember 3.4 compatibility

### ISSUE THREAD

**Issue by simonc** [mitchlloyd/ember-autosave#32]
Hi there,

I've updated an app to Ember v3.4.3 and there seem to be an issue with autosave-proxy trying to `import Ember from 'ember'` resulting in the following error:

```
Error: Could not find module `ember` imported from `ember-autosave/autosave-proxy`
```

Now that 3.4 is the official LTS, is there any plan to update ember-autosave?

Thanks! ❤️

**Comment by mitchlloyd** [comment]
Thanks for letting me know about this issue. I just pushed a branch [ember-3.4.x-fixes](https://github.com/mitchlloyd/ember-autosave/tree/ember-3.4.x-fixes) that updates the ember-cli version and moves to the new packaging scheme. Hopefully that branch can get you rolling in the short-term. Please let me know if you run into any issues with those changes.

It seems like the packaging changes and a property notification deprecation make this a breaking change, so I'd like to publish this as a 2.0 and take the opportunity to remove all deprecations as well as some "ye olde Ember" quirks in this library which I'll track in the [2.0 roadmap issue](https://github.com/mitchlloyd/ember-autosave/issues/21). I expect to be able to release 2.0 by 11/5/2018.

**Comment by simonc** [comment]
@mitchlloyd I just tried it and it works very well! Thank you! 😊

**Comment by mitchlloyd** [comment]
@simonc Released version 3.0. There is an api change to be aware of: https://github.com/mitchlloyd/ember-autosave#upgrading-to-30

**Comment by simonc** [comment]
@mitchlloyd Awesome! Thanks a lot!

**Comment by simonc** [comment]
@mitchlloyd I think the README might need to be updated too since it references `import Ember from 'ember';` 🙂

**Comment by mitchlloyd** [comment]
Updated the README with new-style Ember imports in cb89882.
