### ISSUE TITLE
autosave('model') Not Reacting to Model Updates

### ISSUE THREAD

**Issue by jcfinnerup** [mitchlloyd/ember-autosave#35]
Hi there, 

Im using ember 3.0 and i have tried to implement Autosave on both the Component, Route and Controller level. 

**Code:**

``` 
import autosave from 'ember-autosave';

export default Component.extend({
  post: autosave('model.candidate')
});

```

### What i Expect to happen
 - Model changes are registered, and the Save() function is fired

### What actually Happens
 - Nothing, theres no log, no error or anything. 

I have tried to make a computed property listening to the same model, and this does fire as expected:

Any help would be greatly appreciated. 

Best, 
Jens

**Comment by jcfinnerup** [comment]
Alright i figured out that i was using this incorrectly

My issue was that i didnt understand that i had to pass the autosave property to the input fields as the model. The word "post" has slightly confusing for me.

**Comment by mitchlloyd** [comment]
@jcfinnerup I agree that the word "post" is mostly meaningless in the readme. I changed this to `modelWithAutosave` to better explain what is going in the examples. Please reopen this issue if you don't think that documentation fix helps.

**Comment by jcfinnerup** [comment]
Thanks a lot Mitch, I think that would help in case someone shares my
confusion down the road.
